### PR TITLE
feat(movement): RETARD MOVES LESSS GOOOOOOOO

### PR DESCRIPTION
**Pull request by k0ded**

### CODE REVIEW

**Comment by k0ded** [comment]
(less goooo)[https://media.pitchfork.com/photos/5c7d4c1b4101df3df85c41e5/1:1/w_600/Dababy_BabyOnBaby.jpg]!

**Review by olchyk98 — APPROVED** [review]

**Comment by k0ded** [comment]
LESS GOOO

**Comment by olchyk98** [comment]
Let's go!
Make no excuses now
I'm talking here and now
I'm talking here and now
Let's go!
Your time is running out
I'm talking here and now
I'm talking here and now
It's not about what you've done
It's about what you doing
It's all about where you going
No matter where you've been
Let's go!
Let's go!
Let's go! Let's go!
Hey! Its now or never
Let's go!
Oh let's go!
There ain't no better time
I'm talking here and now
I'm talking here and now
Let's go!
Right now is where you shine
I'm talking here and now
I'm talking here and now
It's not about what you've done
It's about what you doing
It's all about where you going
No matter where you've been
Let's go!
Let's go!
Let's go!…

**Comment by k0ded** [comment]
Pooh, you a fool for this one
Ha
Oh lord, Jetson made another one
Hah
Pack in the mail, it's gone (Uh)
She like how I smell, cologne (Yeah)
I just signed a deal, I'm on
Yeah, yeah
I go where I want
Good, good
Play if you want, let's do it (Ha)
I'm a young CEO, Suge (Yeah)
Yeah, yeah
The first nigga play, I'ma body a nigga (Ha)
I just checked my balance
I'll probably pull up to your hood
And come buy me a nigga (No cap)
You know that your ho told you that nigga crazy
Don't think that she lied to you, nigga (Bitch)
Get caught with your ho when I'm poppin' 'em both
Now they high just like Bobby and Whitney (Haa)
Say I'm the goat, act like I don't know
But fuck it, I'm obviously winning
Don't make me go hit the bank
And take out a hundred
To show you our pockets are different (Ha)
I'm out with your bitch and I only want knowledge
She got a lil' mileage, I'm chillin' (Uh)
You disrespect me and I'll beat your ass up
All in front of your partners and children (Ahh, ahh)
I'm the type to let a nigga think that I'm broke
Until I pop out with a million (I pop)
Take 20K and put that on your head
And make one of your partners come kill you (Yeah)
Say he fuckin' with me then he gotta grow up
'Cause this nigga gotta be kiddin' (Kiddin')
This shit, it can't fit in my pocket
I got it, like I hit the lottery, nigga (Hot, hot, hot)
Opp, I'll slap the shit out a nigga
No talkin', I don't like to argue with niggas (I don't)
Ain't gon' be no more laughin'
You see me whip out guns
I'm gon' shot me a nigga (No cap)
I don't follow no bitches on IG
But all of your bitches, they follow a nigga (Ha)
And that lil' nigga ain't gon' shoot shit with that gun
He just pull it out in his pictures (Bitch, uh)
Hah
Pack in the mail, it's gone (Uh)
She like how I smell, cologne (Yeah)
I just signed a deal, I'm on
Yeah, yeah
I go where I want
Good, good
Play if you want, let's do it (Ha)
I'm a young CEO, Suge (Yeah)
Yeah, yeah
Hah
Pack in the mail, it's gone (Uh)
She like how I smell, cologne (Yeah)
I just signed a deal, I'm on
Yeah, yeah
I go where I want
Good, good
Play if you want, let's do it (Ha)
I'm a young CEO, Suge (Yeah)
Yeah, yeah
Talkin' 'bout, "Shit I'm gon' pop that" (Pop)
Got like thirty-two thousand in one of my pockets
The other one, that's where the Glock at (Glock)
You little nigga wanna be internet gangster
Man, tell all these little niggas stop that (Ha)
Beat and burnt me a nigga in front of the store
Where your mammy and grandmama shop at
(Bitch)
Hopped out on a whole other wave from these niggas
Let's see one of you little niggas top that
I will turn a nigga into a convertable
Push me a lil' nigga top back (Vroom)
Her boyfriend be hatin' and callin' her groupie
Just 'cause she like all my music (Ha)
She'll send me a text and then delete the message
He tryna find out, it's confusing
I don't know what these niggas is thinking about
Use the brain in your head 'fore you lose it (Bitch)
I'll pull up after school and I'll teach her some shit
Tell your bro I'm a motherfuckin' tutor
'Member I used to cheat off of pretty bitch test
All the teachers, they thought I was stupid (Uh huh)
Was expecting the Boxer to pull up on a trap
Man, this nigga pulled up on a scooter (The fuck?)
Hah
Pack in the mail, it's gone (Uh)
She like how I smell, cologne (Yeah)
I just signed a deal, I'm on
Yeah, yeah
I go where I want
Good, good
Play if you want, let's do it (Ha)
I'm a young CEO, Suge (Yeah)
Yeah, yeah
Hah
Pack in the mail, it's gone (Uh)
She like how I smell, cologne (Yeah)
I just signed a deal, I'm on
Yeah, yeah
I go where I want
Good, good
Play if you want, let's do it (Ha)
I'm a young CEO, Suge (Yeah)
Yeah, yeah

**Pull request merged**
